### ISSUE TITLE
ERR_20241219085425 - BioClip reply 500 - TypeError: fetch failed

### ISSUE THREAD

**Issue by boly38** [boly38/botEnSky#111]
500 BioClip replyTo

server logs
````
19-12-2024 08:54:15.673 [info ] 🧾️BlueSkyService - searchPosts {"q":"#photography #bird","sort":"latest","limit":40,"since":"2024-12-17T07:54:14.033Z","until":"2024-12-19T07:54:15.049Z"} - 34 results, 20 post-filter
19-12-2024 08:54:15.763 [info ] 🧾️PluginsCommonService - 🖥️ BioClip  👤 `REDACTED 20 candidate(s)
19-12-2024 08:54:15.764 [info ] 🧾️GrBirdApiService - Bioclip classification for the following image : https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:r7mgj36ccnapkparsnrnbkxz/bafkreicr5abzwlhdlqyomgro5p3u5mhn72vd2m5peqo4mthkale7vudpi4@jpeg
19-12-2024 08:54:25.278 [info ] 🧾️BioClip - result:OK {"species":"Archilochus colubris","scoredResult":"BioClip identify (at 75.79%) Archilochus colubris genus:Archilochus (fam. Trochilidae) com. Ruby-throated Hummingbird\n\nAvibase flickr\nhttps://tinyurl.com/28ugf6qf"}
19-12-2024 08:54:25.369 [error] 🧾️PluginsCommonService - 🖥️ BioClip  👤 REDACTED replyTo TypeError: fetch failed
19-12-2024 08:54:25.462 [error] 🧾️PluginsCommonService - 🖥️ BioClip  👤 REDACTED [birdIdentify handle response] Impossible d'identifier l'image de https://bsky.app/profile/pinky6460.bsky.social/post/3ldneiqi7hc2y avec BioClip : impossible de répondre au post
19-12-2024 08:54:25.463 [error] 🧾️ExpressServer - Error id:ERR_20241219085425 msg:BioClip unexpected error mustBeReported:true
19-12-2024 08:54:25.464 [info ] 🧾️News 📢 - Unexpected error 500, please look for or report it on  <a href="https://github.com/boly38/botEnSky/issues">issues</a> - ERR_20241219085425
````

**Comment by boly38** [comment]
- simulation cant reproduce issue
- will reply using debug mode but locally: response will be not visible from bot page

**Comment by boly38** [comment]
new `ERR_20241223115422 `

````
23-12-2024 11:54:13.369 [info ] 🧾️BlueSkyService - searchPosts {"q":"#photography #bird","sort":"latest","limit":40,"since":"2024-12-21T10:54:11.707Z","until":"2024-12-23T10:54:12.688Z"} - 39 results, 22 post-filter
23-12-2024 11:54:13.370 [info ] 🧾️PluginsCommonService - 🖥️ BioClip  👤 REDACTED  candidate(s)
23-12-2024 11:54:13.371 [info ] 🧾️GrBirdApiService - Bioclip classification for the following image : https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:ted2ihzvuw2xhbznmayefez5/bafkreidtto6xhfrdbbdfdpfswv5q5rfhznvzjrzanr6a22itkz7mdjnswy@jpeg
undefined
Trace
    at BioClip.process (file:///opt/render/project/src/src/plugins/BioClip.js:86:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BotService.process (file:///opt/render/project/src/src/services/BotService.js:65:28)
    at async ExpressServer.hookResponse (file:///opt/render/project/src/src/services/ExpressServer.js:140:17)
23-12-2024 11:54:22.287 [error] 🧾️PluginsCommonService - 🖥️ BioClip  👤 REDACTED  [birdIdentify] Impossible d'identifier l'image de https://bsky.app/profile/davisantwi.bsky.social/post/3ldxomp7d7c2z avec BioClip : null
23-12-2024 11:54:22.287 [error] 🧾️ExpressServer - Error id:ERR_20241223115422 msg:BioClip unexpected error mustBeReported:true
23-12-2024 11:54:22.369 [info ] 🧾️News 📢 - Unexpected error 500, please look for or report it on  <a href="https://github.com/boly38/botEnSky/issues">issues</a> - ERR_20241223115422
````
