### ISSUE TITLE
replyTo 400 

### ISSUE THREAD

**Issue by boly38** [boly38/botEnSky#61]
botEnSky is unable to reply 
- to this post: https://bsky.app/profile/neoresistant.bsky.social/post/3kvopsv5hwk2m
- embedding this image : https://bs.plantnet.org/image/o/a1079db51c9eddcc35b184b759730d701db9bbac

````
25-06-2024 12:54:26.928 [info ] 🧾️PlantnetApiService - Pla@ntNet identify following image : https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:umlxafzutkwwnbonfpz7iazr/bafkreid6fwibnbokwfzig5bvcmzm35wofiwby5plgutjbcb4gtooo22y2m@jpeg
25-06-2024 12:54:32.695 [error] 🧾️PlantnetCommonService - 🖥️ Plantnet  👤 REDACTED replyTo {
  "status": 400,
  "error": "InvalidRequest",
  "success": false,
  "headers": {
    "access-control-allow-origin": "*",
    "content-length": "123",
    "content-type": "application/json; charset=utf-8",
    "date": "Tue, 25 Jun 2024 10:54:32 GMT",
    "etag": "W/\"7b-5OYjOucrkx456vG6nIBiH/VZWIA\"",
    "keep-alive": "timeout=90",
    "ratelimit-limit": "5000",
    "ratelimit-policy": "5000;w=3600",
    "ratelimit-remaining": "4997",
    "ratelimit-reset": "1719316472",
    "strict-transport-security": "max-age=63072000",
    "vary": "Accept-Encoding",
    "x-powered-by": "Express"
  }
}
25-06-2024 12:54:32.696 [info ] 🧾️PlantnetCommonService - Unable to make bluesky embed of image https://bs.plantnet.org/image/o/a1079db51c9eddcc35b184b759730d701db9bbac, so keep it as text link: impossible de répondre au post
25-06-2024 12:54:32.911 [error] 🧾️PlantnetCommonService - 🖥️ Plantnet  👤 REDACTED replyTo {
  "status": 400,
  "error": "InvalidRequest",
  "success": false,
  "headers": {
    "access-control-allow-origin": "*",
    "content-length": "123",
    "content-type": "application/json; charset=utf-8",
    "date": "Tue, 25 Jun 2024 10:54:32 GMT",
    "etag": "W/\"7b-5OYjOucrkx456vG6nIBiH/VZWIA\"",
    "keep-alive": "timeout=90",
    "ratelimit-limit": "5000",
    "ratelimit-policy": "5000;w=3600",
    "ratelimit-remaining": "4994",
    "ratelimit-reset": "1719316472",
    "strict-transport-security": "max-age=63072000",
    "vary": "Accept-Encoding",
    "x-powered-by": "Express"
  }
}
25-06-2024 12:54:32.912 [error] 🧾️PlantnetCommonService - 🖥️ Plantnet  👤 REDACTED Impossible d'identifier l'image de https://bsky.app/profile/neoresistant.bsky.social/post/3kvopsv5hwk2m avec Plantnet : impossible de répondre au post
````

**Comment by boly38** [comment]
local try to reproduce
````
$ node.exe tests/manual/bluesky_post_with_image.js
C:\WORK\perso\botEnSky\node_modules\@atproto\xrpc\dist\client.js:106
                throw new types_1.XRPCError(resCode, res.body.error, res.body.message, res.headers);
                      ^

XRPCError: Input must have the property "identifier"
    at ServiceClient.call (C:\WORK\perso\botEnSky\node_modules\@atproto\xrpc\dist\client.js:106:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BskyAgent.login (C:\WORK\perso\botEnSky\node_modules\@atproto\api\dist\agent.js:214:25)
    at async file:///C:/WORK/perso/botEnSky/tests/manual/bluesky_post_with_image.js:9:1 {
  status: 400,
  error: 'InvalidRequest',
  success: false,
  headers: {
````

**Comment by boly38** [comment]
maybe login of first search was no more available for reply service (two svc instance)

**Comment by boly38** [comment]
the replyMessage attempted to be send is 
````
"replyMessage":"Pl@ntNet identifie (à 82.39%) Lathyrus latifolius (fam Fabaceae) com. Pois de senteur, Pois vivace, Bonjour il est bien dommage de nommer pois de senteur la gesse latifolia qui n'a aucune senteur cela crée une confusion avec Lathyrus odoratus plante parfumées et menacé bien à vous Daniel Bourget
#BeSPlantnet #IndentificationDePlantes"
````
So 340 ; where the post limit is 300

**Comment by boly38** [comment]
PlantNet answers to my contact message: negative vote should arrive soon to improve collaborative moderation. Related CN entry has been fixed.
