### ISSUE TITLE
ERR_20240903203957 - fetch search issue (again)

### ISSUE THREAD

**Issue by boly38** [boly38/botEnSky#83]
Following #79 - reproduced same issue at search time

````
2024-09-03 20:39:57.158 [botensky_prod] [ERROR] Error id:ERR_20240903203957 msg:Plantnet unexpected error stack:undefined
````
![image](https://github.com/user-attachments/assets/506ea6f2-365e-4db1-9bd2-3892a59e115d)

![image](https://github.com/user-attachments/assets/cab00294-d313-41eb-bc67-e67e13bffb91)

think about
- retry mechanism
- more details on error - if easy to reproduce (server side)
- (suspect transient network issue, or maybe hidden login session token expiration?)

**Comment by boly38** [comment]
I'm able to reproduce this reject error message in the following condition
- connected to Internet
- bluesky client login
- sleep
- during sleep, plug-off network (no Internet)
- bluesky feed search

````
_expectNoError XRPCError: TypeError: fetch failed
    at AtpAgent.defaultFetchHandler [as fetch] (C:\WORK\perso\botEnSky\node_modules\@atproto\xrpc\dist\client.js:135:15)
    at async BskyAgent._fetch (C:\WORK\perso\botEnSky\node_modules\@atproto\api\dist\agent.js:330:19)
    at async ServiceClient.call (C:\WORK\perso\botEnSky\node_modules\@atproto\xrpc\dist\client.js:88:21)
    at async BlueSkyService.searchPosts (file:///C:/WORK/perso/botEnSky/src/servicesExternal/BlueSkyService.js:76:26) {
  status: 1,
  error: 'TypeError: fetch failed',
  success: false,
  headers: undefined
}

(wherelueSkyService.js:76 is)
        const response = await this.api.app.bsky.feed.searchPosts(params, {});

````

**Comment by boly38** [comment]
with fix, this error will be considered a transient, retried and finally marked (internally) as error without "news" entry like below
![image](https://github.com/user-attachments/assets/21306bc9-56d3-4d93-918f-dc1bbbb51b0e)

**Comment by boly38** [comment]
ERR_20240905145631 05/09/2024 14:56 same issue, 
It was before merge of v1.2.9
